services:
  nginx:
    image: nginx:latest
    container_name: leihbase-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "$NGINX_HOST_SOCKET:80"
    networks:
      - leihbar_net
  app:
    container_name: leihbase-app
    build:
      context: app
      dockerfile: Dockerfile
      target: dev
    environment:
      NUXT_PUBLIC_POCKETBASE_SERVER_BASE_URL: "http://leihbase-pocket:8080"
      NUXT_PUBLIC_POCKETBASE_CLIENT_BASE_URL: "$LEIHBASE_URL"
      NUXT_PLAUSIBLE_TRACKING_DOMAIN: "$LEIHBASE_DOMAIN"
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - leihbar_net

  pocketbase:
    container_name: leihbase-pocket
    build:
      context: pocketbase
      dockerfile: Dockerfile
      target: dev
    environment:
      CONFIG_LOCALE: "$LEIHBASE_LOCALE"
      # If a reservation needs to have a user, or not
      CONFIG_RESERVATION_REQUIRE_USER: "$LEIHBASE_RESERVATION_REQUIRE_USER"
      CONFIG_LENDING_CONDITIONS_LINK: "$LEIHBASE_LENDING_CONDITIONS_URL"
      CONFIG_LENDING_CONTACT_EMAIL: "$LEIHBASE_CONTACT_EMAIL"
    volumes:
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_hooks:/pb/pb_hooks
      - ./pocketbase/pb_data:/pb/pb_data
    networks:
      - leihbar_net

  mailhog:
    container_name: leihbase-mail
    image: mailhog/mailhog
    logging:
      driver: "$LEIHBASE_LOGGING"
    ports:
      - $MAILHOG_SMTP_HOST_SOCKET:1025
      - $MAILHOG_UI_HOST_SOCKET:8025 
    networks:
      - leihbar_net

networks:
  leihbar_net:
    name: leihbar_net
